spring:
  application:
    name: order-event-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/order_management
    username: postgres
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080